version: '1.0'
name: pipeline-20240627
displayName: pipeline-20240627
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-a6b969b9
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: 打包
        nodeVersion: 21.5.0
        commands:
          - '"# 打印Node 版本"'
          - node -v
          - '"# 设置NPM源，提升安装速度"'
          - npm config set registry https://registry.npmmirror.com
          - npm i -g pnpm
          - pnpm config set registry https://registry.npmmirror.com
          - '"# 执行编译命令"'
          - pnpm install && pnpm run build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
  - name: stage-fcb6585c
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: deploy@agent
        name: deploy_agent
        displayName: 部署
        hostGroupID:
          ID: 小沐沐吖
          hostID:
            - a6cd50d9-a71a-4db0-befd-c2faf4d02d37
        deployArtifact:
          - source: build
            name: dist
            target: /opt/1panel/apps/openresty/Nginx/www/sites/blog.mu00.cn
            dependArtifact: BUILD_ARTIFACT
        script:
          - cd /opt/1panel/apps/openresty/Nginx/www/sites/blog.mu00.cn
          - tar -xzvf dist.tar.gz
          - rm -rf dist.tar.gz
          - rm -rf index
          - mv -f dist index
          - sudo chmod 0755 /opt/1panel/apps/openresty/Nginx/www/sites/blog.mu00.cn/index
          - echo '部署完成'
        notify: []
        strategy:
          retry: '0'
